server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/tls/cert.pem;
    ssl_certificate_key /etc/nginx/tls/key.pem;

    gzip off;
    autoindex off;

    root /usr/share/nginx/html;

    location / {
        add_header Accept-Ranges bytes always;
    }
}
